version: "3.9"

services:
  smart-expenses-backend:
    container_name: smart-expenses-backend
    restart: always
    command: python3 __main__.py
    env_file: app/.env
    build:
      context: ./app
      dockerfile: app.dockerfile
    depends_on:
      - smart-expenses-db
    ports:
      - "8000:8000"
    networks:
      - app-network

  smart-expenses-db:
    container_name: smart-expenses-db
    image: postgres:16
    env_file: db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network


  smart-expenses-frontend:
    container_name: smart-expenses-frontend
    build:
      context: ./dashboard-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - smart-expenses-backend
    networks:
      - app-network

  # caddy:
  #   image: caddy:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./cert:/etc/caddy/cert
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network

  # frontend:
  #   container_name: frontend
  #   env_file: .env
  #   build:
  #     context: ./front
  #     dockerfile: front.dockerfile
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   restart: "no"
  #   networks:
  #     - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
